//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSWatcherEngineEvent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSWatcherEngineEvent.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DataGrid_Edit {
            get {
                return ResourceManager.GetString("DataGrid.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string DataGrid_Path {
            get {
                return ResourceManager.GetString("DataGrid.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Identifier.
        /// </summary>
        public static string DataGrid_SourceIdentifier {
            get {
                return ResourceManager.GetString("DataGrid.SourceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Editor_Close {
            get {
                return ResourceManager.GetString("Editor.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Raising Events:.
        /// </summary>
        public static string Editor_EnableRaisingEvents {
            get {
                return ResourceManager.GetString("Editor.EnableRaisingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters:.
        /// </summary>
        public static string Editor_Filters {
            get {
                return ResourceManager.GetString("Editor.Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Subdirectories:.
        /// </summary>
        public static string Editor_IncludeSubdirectories {
            get {
                return ResourceManager.GetString("Editor_IncludeSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Filters:.
        /// </summary>
        public static string Editor_NotifyFilters {
            get {
                return ResourceManager.GetString("Editor.NotifyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Editor_Path {
            get {
                return ResourceManager.GetString("Editor.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Identifier:.
        /// </summary>
        public static string Editor_SourceIdentifier {
            get {
                return ResourceManager.GetString("Editor.SourceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Editor_Title {
            get {
                return ResourceManager.GetString("Editor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrottleMs and DebounceMs can&apos;t be combined..
        /// </summary>
        public static string Error_CantConbineThrottleAndDebounce {
            get {
                return ResourceManager.GetString("Error.CantConbineThrottleAndDebounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: &apos;{0}&apos; is invalid.
        /// </summary>
        public static string Error_PathInvalid {
            get {
                return ResourceManager.GetString("Error.PathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSystemWatcher doesn&apos;t work for cmdlet providers of type {0}.
        /// </summary>
        public static string Error_ProviderNotSupported {
            get {
                return ResourceManager.GetString("Error.ProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier &apos;{0}&apos; is already watching path &apos;{1}&apos;.
        /// </summary>
        public static string Error_SourceIdentifierAlreadyInUse {
            get {
                return ResourceManager.GetString("Error.SourceIdentifierAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Trace.
        /// </summary>
        public static string Trace_Clear {
            get {
                return ResourceManager.GetString("Trace.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        public static string Trace_Title {
            get {
                return ResourceManager.GetString("Trace.Title", resourceCulture);
            }
        }
    }
}
