//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSWatcherEngineEvent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSWatcherEngineEvent.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrottleMs and DebounceMs can&apos;t be combined..
        /// </summary>
        public static string Error_CantConbineThrottleAndDebounce {
            get {
                return ResourceManager.GetString("Error.CantConbineThrottleAndDebounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: &apos;{0}&apos; is invalid.
        /// </summary>
        public static string Error_PathInvalid {
            get {
                return ResourceManager.GetString("Error.PathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSystemWatcher doesn&apos;t work for cmdlet providers of type {0}.
        /// </summary>
        public static string Error_ProviderNotSupported {
            get {
                return ResourceManager.GetString("Error.ProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier &apos;{0}&apos; is already watching path &apos;{1}&apos;.
        /// </summary>
        public static string Error_SourceIdentifierAlreadyInUse {
            get {
                return ResourceManager.GetString("Error.SourceIdentifierAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing of the file system watcher options was cancelled by the user.
        /// </summary>
        public static string Message_EditingCanceledByUser {
            get {
                return ResourceManager.GetString("Message.EditingCanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OptionsUI_Cancel {
            get {
                return ResourceManager.GetString("OptionsUI.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debounce notificaton (ms):.
        /// </summary>
        public static string OptionsUI_DebounceMs {
            get {
                return ResourceManager.GetString("OptionsUI.DebounceMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter files by name:.
        /// </summary>
        public static string OptionsUI_FilterWildCardLabel {
            get {
                return ResourceManager.GetString("OptionsUI.FilterWildCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Sub directories.
        /// </summary>
        public static string OptionsUI_IncludeSubDirs {
            get {
                return ResourceManager.GetString("OptionsUI.IncludeSubDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder Attributes have changed (Attributes).
        /// </summary>
        public static string OptionsUI_NotifyOnAttributes {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder has been created (CreationTime).
        /// </summary>
        public static string OptionsUI_NotifyOnCreationTime {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name has changed (Directory).
        /// </summary>
        public static string OptionsUI_NotifyOnDirectory {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name has changed (FileName).
        /// </summary>
        public static string OptionsUI_NotifyOnFileName {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify on:.
        /// </summary>
        public static string OptionsUI_NotifyOnHeader {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder has been accessed (LastAccess).
        /// </summary>
        public static string OptionsUI_NotifyOnLastAccess {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnLastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder has been written to (LastWrite).
        /// </summary>
        public static string OptionsUI_NotifyOnLastWrite {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnLastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files/Folder access rights have been changed (Security).
        /// </summary>
        public static string OptionsUI_NotifyOnSecurity {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder Size has changed (Size).
        /// </summary>
        public static string OptionsUI_NotifyOnSize {
            get {
                return ResourceManager.GetString("OptionsUI.NotifyOnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OptionsUI_Ok {
            get {
                return ResourceManager.GetString("OptionsUI.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string OptionsUI_PathLabel {
            get {
                return ResourceManager.GetString("OptionsUI.PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle notificaton (ms):.
        /// </summary>
        public static string OptionsUI_ThrottleMs {
            get {
                return ResourceManager.GetString("OptionsUI.ThrottleMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify FileSystem Watcher Options.
        /// </summary>
        public static string OptionsUI_Title {
            get {
                return ResourceManager.GetString("OptionsUI.Title", resourceCulture);
            }
        }
    }
}
